---
layout: page
title: R Meetup 시즌 1
subtitle: "2017년 08월 -- 2018년 05월"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: hide
mainfont: NanumGothic
---


```{r setOptions, message=FALSE, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# xwMOOC R Meetup


xwMOOC R Meetup은 KRUG 1,2대 회장을 역임한 유충현님을 모시고 xwMOOC 이광춘, 캐글뽀개기 이상열이 십시일반 
노력을 하여 2017년 8월 ~ 2018년 5월까지 매월 총 10회 진행되었습니다.
KossLab(공개SW 개발자센터)의 공간지원을 받아 나름 쾌적한 환경에서 R 사용자들이 모여 즐거운 배움과 네트워킹 시간을 갖게되었습니다.

- 주관 : [xwMOOC](https://www.facebook.com/xwmooc/)
- 운영: [캐글뽀개기](https://www.facebook.com/groups/kagglebreak/)
- 장소 : 토즈 강남점 / 선릉 패스트파이브
- 매달 셋째주 수요일


# xwMOOC R Meetup 발표자료 모음



|요일   |주제   |발표자   |발표자료   |     비고          |
|-------|-------|---------|-----------|-------------------|
|2017.08.23(수)|감성분석(Sentiment Analysis) - 깔끔한 텍스트 방식(tidytext)|이광춘|[발표자료](http://statkclee.github.io/ml/ml-sentiment.html)
|              |modelr |이상열 |[발표자료](kaggle/Meetup_1/modelr/modelr_example.md)
|2017.09.20(수)|쉽게 배우는 R 데이터분석 |김영우|[발표자료](kaggle/Meetup_2/Easy_R_write/EasyR_%EA%B9%80%EC%98%81%EC%9A%B0.pdf)
|              |재현가능한 연구를 위한 데이터 과학 제품 개발 |이광춘|[발표자료](https://statkclee.github.io/viz/viz-low-birth-rate.html)
|              |한글 텍스트데이터 분석 |류충현|[발표자료](kaggle/Meetup_2/text_analytics/%EB%8C%80%ED%86%B5%EB%A0%B9%EC%97%B0%EC%84%A4%EB%AC%B8%EB%B6%84%EC%84%9D_%EC%9C%A0%EC%B6%A9%ED%98%84_20170920.pdf)
|2017.10.18(수)|R 로 웹 데이터를 가져오는 4가지 방법(은 크롤링)|박찬엽|[발표자료](kaggle/Meetup_3/crawling/getWebR.pdf)
|              |데이터과학 블로그 10분 완성|이광춘|[발표자료](https://statkclee.github.io/ds-authoring/ds-blogdown.html)
|              |테드(TED) 에듀데이터 분석|한수미|[발표자료](kaggle/Meetup_3/ted/TED_Edu_Corpus_Analysis_%ED%95%9C%EC%88%98%EB%AF%B8.ipynb)
|              |Shiny의 기본 원리와 이해|김승욱|[발표자료](kaggle/Meetup_3/shiny/r_meetup_shiny.pdf)
|2017.11.15(수)|통계모형 시각화|이광춘|[발표자료](https://statkclee.github.io/statistics/stat-model-visualization.html)
|              |R언어 역사|이광춘|[발표자료](https://statkclee.github.io/data-science/ds-r-lang.html)|
|              |catboost 소개|이상열|[발표자료](kaggle/Meetup_4/catboost_introduction.ipynb)|
|2017.12.21(목)|LASSO regresion을 이용한 Taxonomy|류충현|[발표자료](kaggle/Meetup_5/taxonomy/02_Documents_Texonomy_Slide.pdf)
|              |메타분석(Meta analysis)|김가경|[발표자료](kaggle/Meetup_5/MetaAnalysis/20171221_MetaAnalysis.nb.html)|
|              |시계열 데이터 예측|이광춘|[발표자료](https://statkclee.github.io/statistics/stat-time-series-forecast.html)|
|2018.01.17(수)|h2o 소개|황문기|[발표자료](kaggle/Meetup_6/h2o_%EC%82%AC%EB%A1%80/XwMooc%20R%20Meetups%206%ED%9A%8C_%EC%84%B8%EC%85%981_%ED%99%A9%EB%AC%B8%EA%B8%B0_20180117.pdf)
|              |Spark R 소개|지용기|[발표자료](kaggle/Meetup_6/SparkR%EC%86%8C%EA%B0%9C/SparkR%EC%86%8C%EA%B0%9C.pdf)|
|              |Code Snippets: batch jobs in R(라이트닝 토크)|어수행|[발표자료](https://github.com/sooheang/batch-jobs-R/blob/master/slide/BatchJobsR_xwMooc.pdf)|
|              |Code Snippets:R 암호화폐|이광춘|[발표자료](https://statkclee.github.io/finance/finance-blockchain.html)|
|2018.02.21(수)|빅데이터는 디스크에 쓰고 R 메모리라고 읽는다|이광춘|[발표자료](https://statkclee.github.io/bigdata/bigdata-bigmemeory.html)|
|              |한국 영화배우 데이터로 만든 한국판 케빈 베이컨 놀이|나성호|[발표자료](https://mrkevinna.github.io/SixDegreesOfKoreanActors/)|
|              |데이터 정규화를 통한 Feature Selection|장윤경|[발표자료](https://rpeople.github.io/r/2018/02/21/feature_selection)| 부존재 |
|2018.03.21(수)|R과 shiny를 이용한 web application 제작|문건웅|[발표자료](https://github.com/cardiomoon/shinyLecture2)|
|              |Shiny Drill Down|이희재|[발표자료](kaggle/Meetup_8/shiny_drilldown/presentation.html)|
|              |Rstudio 컨퍼런스 후기|양승훈|[발표자료](https://drive.google.com/drive/folders/1aGzlXGjL-3AyYF85A08RoTkhNLft7bwv)|
|2018.04.25(수)|언론사 데이터 저널리즘|배여운|비공개|
|              |데이터는 알고있다|김영우|[발표자료](https://docs.google.com/document/d/1HpytnksNrW3SC2EsulL9CqQlpqddznuJmCDAMQZ_DU0/edit?usp=sharing)|
|              |백 마디 말보다 그래프 하나 - ggplot|이광춘|[발표자료](https://statkclee.github.io/data-product/data-journalism-working-pop.html)|
|              |라이트닝 토크 - 에너지 데이터 분석|김설기|[발표자료](https://akkou.github.io/public/#/)|
|              |라이트닝 토크 - 뉴스기사 솔루션 (키워드, 문장요약, 분류기) 소개|황문기|[발표자료](kaggle/Meetup_9/R%20Meetup%209%ED%9A%8C_%EC%84%B8%EC%85%985_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%20%EB%89%B4%EC%8A%A4%EA%B8%B0%EC%82%AC%20%EB%B6%84%EC%84%9D%EC%BC%80%EC%9D%B4%EC%8A%A4_%ED%99%A9%EB%AC%B8%EA%B8%B0_20180425.pdf)|
|2018.05.23(수)|R 패키지: 신규 패키지 소개 - dlookr|류충현|[발표자료](kaggle/Meetup_10/01_Understanding_dlookr.pdf)|
|              |CRAN으로 거쳐가는 정거장 - Github suggetR 패키지|이광춘|[발표자료](https://statkclee.github.io/data-science/r-pkg-suggestK.html#)|


